### ISSUE TITLE
No push notifications

### ISSUE THREAD

**Issue by aftmostheart2** [khcrysalis/Feather#101]
I got enmity installed via feather and I disabled ppq check protections and still I don’t get any push notifications, I checked through iPhone notifications anll of it is turned on and still nothing. I got the cert from signulous and on there I can sign it and check a box and I would always get notifications from my apps. But from feather I can’t seem to figure out what to do

**Comment by khcrysalis** [comment]
You will need to resign without the option enabled

**Comment by aftmostheart2** [comment]
I'm sorry is there anything I can do to fix this?

**Comment by khcrysalis** [comment]
Sign the application without the appended string done by the ppqcheck protection option and then install, all notifications need is entitlements and the exact identifier found on the appstore.

**Comment by khcrysalis** [comment]
People have confirmed notifications work by not having ppqcheck option enabled and signing.

**Comment by khcrysalis** [comment]
Otherwise, you may be doing something wrong.

**Comment by ball1501** [comment]
> People have confirmed notifications work by not having ppqcheck option enabled and signing.

How go disable ppq check? Im newbie

**Comment by GottaLoveAng** [comment]
Settings > Signing Options > Enable Protection

**Comment by atuncer** [comment]
> Settings > Signing Options > Enable Protection

Yeah I missed this part on wiki [(Using an Apple Developer Account > Gathering Files)](https://github.com/khcrysalis/Feather/wiki/Using-an-Apple-Developer-Account#gathering-files)

I used a XC wildcard p12 and mobileprovision instead of the required ones.

Thx for the help
