### ISSUE TITLE
Apps Update

### ISSUE THREAD

**Issue by TheSrBig** [khcrysalis/Feather#107]
As in the case of Scarlet, it would be good if apps could be updated if a new version is released in each repo, or in other repos if it is the same bundle id with a new version.

**Comment by khcrysalis** [comment]
I decided against this as no repository follows a basic scheme of having a unique identifier for each app, so its hard to see if apps need an update.

**Comment by TheSrBig** [comment]
> I decided against this as no repository follows a basic scheme of having a unique identifier for each app, so its hard to see if apps need an update.

But the Scarlet one works, if you change the version
