### ISSUE TITLE
Installing tweaked ipa on top of stock ipa doesn't work

### ISSUE THREAD

**Issue by gototheskinny** [khcrysalis/Feather#110]
Installing on top of previously installed specifically Tiktok stock ipa [https://t.me/BHTikTokPlusPlus/25](https://t.me/BHTikTokPlusPlus/25) after this ipa Bhtiktok++ ipa [https://t.me/BHTikTokPlusPlus/22](https://t.me/BHTikTokPlusPlus/22) doesn't work.

For this ipa to work you need to install the stock decrypted ipa>sign in to your account> **_install the tweaked ipa_** (this isn't working and gives error) 

so this is a little situational. uploaded the error screen recording down below:
[https://streamable.com/pombiv?src=player-page-share](https://streamable.com/pombiv?src=player-page-share)

--This installation works perfectly with esign

Using **v1.0.4**
**DNS** method [https://sideloading.vercel.app/feather-guide.html](https://sideloading.vercel.app/feather-guide.html)
Ios 17.3.1
iphone 14 pro

**Comment by khcrysalis** [comment]
If iOS doesnt want to accept it then I don't think I can do much about it.

**Comment by khcrysalis** [comment]
But you can try to use the online install method instead to see if it works

**Comment by gototheskinny** [comment]
> If iOS doesnt want to accept it then I don't think I can do much about it.

Esign is able to do this tho.

**Comment by khcrysalis** [comment]
All feather uses to install is opening a url 🤷

**Comment by gototheskinny** [comment]
> All feather uses to install is opening a url 🤷

Oh I guess esign has something else to be able to do this then. Anyways thank you for checking the issue.
