### ISSUE TITLE
Repo Source

### ISSUE THREAD

**Issue by I-794** [khcrysalis/Feather#117]
If its possible, a repo source for altstore/sidestore to install from there.

**Comment by GottaLoveAng** [comment]
there already is one, just press and hold on the default repo in the app and copy the link and paste it into sidestore/altstore.

**Comment by I-794** [comment]
> https://bit.ly/Altstore-complete
> 
> https://repo.apptesters.org
> 
> https://ipa.cypwn.xyz/cypwn.json
> 
> https://github.com/khcrysalis/Feather/raw/main/app-repo.json
> 
> https://flyinghead.github.io/flycast-builds/altstore.json
> 
> https://alts.lao.sb
> 
> https://hann8n.github.io/JackCracks/MovieboxPro.json
> 
> https://altstore.oatmealdome.me/
> 
> https://theodyssey.dev/altstore/odysseysource.json
> 
> https://raw.githubusercontent.com/vizunchik/AltStoreRus/master/apps.json
> 
> https://pokemmo.com/altstore/
> 
> https://provenance-emu.com/apps.json
> 
> https://bit.ly/40Isul6
> 
> https://bit.ly/Quantumsource
> 
> https://bit.ly/Quantumsource-plus
> 
> https://randomblock1.com/altstore/apps.json
> 
> https://community-apps.sidestore.io/sidecommunity.json
> 
> https://tiny.one/SpotC
> 
> https://taurine.app/altstore/taurinestore.json
> 
> https://alt.getutm.app
> 
> https://wuxu1.github.io/wuxu-complete.json
> 
> https://bit.ly/wuxuslibraryplus
> 
> https://driftywinds.github.io/AltStore/apps.json
> 
> https://ish.app/altstore.json
> 
> https://aio.yippee.rip/repo.json
> 
> https://esign.yyyue.xyz/app.json

Thank you!
