### ISSUE TITLE
Dark Mode Icon

### ISSUE THREAD

**Issue by juliancruzsanchez** [khcrysalis/Feather#119]
I would love to see a dark mode icon, it’s one of the few apps on my home screen that don’t have a dark mode icon for iOS 18.

**Comment by brynts** [comment]
if you want dark & tinted mode icon, you can build from my tree:
https://github.com/brynts/Feather/tree/iOS-18-icon

**Comment by khcrysalis** [comment]
Added in https://github.com/khcrysalis/Feather/commit/9a6c604aeeece5b00285971c6023fd4fbe97c147, will be available next release.
