### ISSUE TITLE
Stuck on app ready to install

### ISSUE THREAD

**Issue by PixelHir** [khcrysalis/Feather#12]
![image](https://github.com/user-attachments/assets/6cb01807-b547-48ef-bd6a-349c72651cbd)
Trying to install any app makes the app just stuck on the app ready to install screen.
I AM on iOS 18 DB though, I'm not sure if this can be the cause.

**Comment by khcrysalis** [comment]
iOS 18 recently has been having issues with http servers in general, sadly not much I can do.

It varies between people and their signers, for example, maplesign wouldn't work but feather does, etc.

The really one thing you can try to do is avoid being on beta software so when the final release happens there can be people who find a proper solution on something everyone has access to.

**Comment by PixelHir** [comment]
Sure thank you. Just wanted to confirm whether this is iOS 18 bug

**Comment by khcrysalis** [comment]
Check https://github.com/khcrysalis/Feather/releases/tag/v1.0.2
