### ISSUE TITLE
Feather ipa sign not working

### ISSUE THREAD

**Issue by Cc78time** [khcrysalis/Feather#122]
Issue stuck on ready to install and stuck on online install to this issue is happening to me. I am on iOS 18.0 
![IMG_1836](https://github.com/user-attachments/assets/3a782313-9f34-4f89-9ddd-e60ea5a75b11)
![IMG_1837](https://github.com/user-attachments/assets/64939f3a-b6a8-46e7-894d-82218835be38)
![IMG_1838](https://github.com/user-attachments/assets/ad99407b-ca36-4318-b688-416a0ade346a)

**Comment by NUTSU7** [comment]
Same issues for me tried changing dns from 0.0.0.0 to google dns, tried vpn, tried other WiFis, tried other versions idk what more to try

**Comment by NUTSU7** [comment]
> > Same issues for me tried changing dns from 0.0.0.0 to google dns, tried vpn, tried other WiFis, tried other versions idk what more to try
> 
> 
> 
> You mean 1.1.1.1, right?

No

**Comment by MatteoNet** [comment]
Same issue

**Comment by khcrysalis** [comment]
Refer to: https://github.com/khcrysalis/Feather/issues/78, and yes it's being worked on. Also for local installation, unlikely to fix as you need proper entitlements for it to work.
