### ISSUE TITLE
JIT enabler?

### ISSUE THREAD

**Issue by ant-7802** [khcrysalis/Feather#125]
Could you add a feature to enable jit?

**Comment by Erisfiregamer1** [comment]
Enabling JIT isn't that easy unfortunately

**Comment by AushevAhmad** [comment]
I don't think enabling JIT is even possible using a developer certificate..

**Comment by Erisfiregamer1** [comment]
It is possible, however you would need a Development type certificate instead of the Distribution one most common signing certificates provide.

**Comment by khcrysalis** [comment]
I don't plan on adding a feature for this, however you can probably achieve it with some external tool with the get-task-allow entitlement.
