### ISSUE TITLE
Some UI dedicated suggestions

### ISSUE THREAD

**Issue by AushevAhmad** [khcrysalis/Feather#126]
1. In the Sources tab instead of using "Add Repo" it should be just "Add".
Why? Because it's expected that if you're gonna click "Add" you're gonna add a repository(cuz, that tab is literally dedicated for them) and I think that "Add Repo" itself sounds weird idk
2. In the Library there should be a counter for downloaded apps too
Why? Because signed apps have one and downloaded ones don't? It just doesn't make sense to me.
3. If PPQcheck Protections option is disabled, then.. why does it say that it's enabled?
![IMG_0465](https://github.com/user-attachments/assets/882b912c-7b8f-4458-a9cf-d0c681b931f8)
4. Kinda the same thing as the 3rd one
![IMG_0466](https://github.com/user-attachments/assets/1f1d538f-d1f7-497a-903c-8acb7d47fd5d)
Like.. why is there a check mark even if the option is disabled? At this point it should be green and have a check mark if PPQcheck is enabled and red with a crossed mark if it's disabled.
5. Those random identifier options should collapse or smth if PPQcheck Protections option is disabled
Why? Because those options are kinda pointless if the PPQcheck is disabled..
![IMG_0467](https://github.com/user-attachments/assets/33a3a776-9b7b-4830-b519-1909394718d1)

**Comment by khcrysalis** [comment]
One thing about PPQCheck, PPQCheck =/= PPQCheck protections

Your certificate has PPQCheck set as true and *cannot* be changed for that file.

**Comment by khcrysalis** [comment]
PPQCheck is an apple certificate thing
PPQCheck protections is a toggle in settings to try and work around it.

Dont get them confused.

**Comment by AushevAhmad** [comment]
Oh, my bad, sorry!

**Comment by khcrysalis** [comment]
Counter added in https://github.com/khcrysalis/Feather/commit/266ffe91378f40b9aaf657e07b6c14030169c20d, will be available in next release.

As for the other features, the ppqcheck notice is gone. And im not changing the localization
