### ISSUE TITLE
See the udid inside if feather

### ISSUE THREAD

**Issue by SteZzy0ne** [khcrysalis/Feather#132]
Can you make a section to see the udid inside feather ? That would make it easier when buying certs to quickly copy the udid

**Comment by khcrysalis** [comment]
Apple doesnt allow you to see your own UDID like that unless we use some sort of profile or you needing to manually enter it in. Sorry, but please just use something like https://udid.tech

**Comment by asdfzxcvbn** [comment]
would you take pr for this? reading embedded.mobileprovision and making sure theres only 1 udid present is a nice way to get the devices udid, and a "UDID Not Found" text could be added in case of an error

personally i kinda like this idea

**Comment by khcrysalis** [comment]
You wouldnt be able to do this with *many* certificates

**Comment by asdfzxcvbn** [comment]
> You wouldnt be able to do this with *many* certificates

i know a good handful of certificate providers that give out mobileprovisions with only the customers udid provisioned, so it'd still be useful for these people
