### ISSUE TITLE
No push notifications

### ISSUE THREAD

**Issue by queermeet-dev** [khcrysalis/Feather#133]
I installed Instagram rocket and another version of Instagram (with nylon tweak) via Feather with my own push certificate.

When the app is closed I do not get any push notifications even though they are enabled.

When I don't close the app but keep it in the background I get push notifications for the first few minutes and then the same result no push notifications 

When I install the same IPA with the same certificate over another provider like AppDB, it works without any problems and they even get push notifications when the app is completely closed.

There is no such option on Feather to activate push notifications therefore I think that push is enabled by default.

I am using Feather version 1.0.5 on an iPhone 15 with iOS 18.0.1.

**Comment by AushevAhmad** [comment]
Try disabling PPQcheck Protections

**Comment by GottaLoveAng** [comment]
disable ppqcheck protections, make sure the bundleid matches the one from the app store and not to change it, make sure you're using a "distribution" certificate and not a developer certificate.

**Comment by queermeet-dev** [comment]
> disable ppqcheck protections, make sure the bundleid matches the one from the app store and not to change it, make sure you're using a "distribution" certificate and not a developer certificate.


Already tried disabling ppqcheck  

When installing the same IPA over AppDB, everything works fine.

I load the ipa into feather, sign it and then install it, no changes are made

**Comment by GottaLoveAng** [comment]
have you imported the same certificate to appdb or are you using a free one?

**Comment by queermeet-dev** [comment]
Okay, I got it working.

Completely uninstalled instagram, resigned it again and then installed it without the PPQCheck


Thanks everyone
