### ISSUE TITLE
Any other options with PPQCheck?

### ISSUE THREAD

**Issue by jekkkk** [khcrysalis/Feather#134]
Really paranoid about getting my account flagged (it isn't mine and is used for legit, published ios apps) and was seeing if there was another way of getting notifications without triggering the PPQCheck. 

- Would changing the Bundle ID to something random work (eg. com.banana.grape) when signing though the app? 
- Why couldn't I add notif capabilities to the App ID/identifier/Bundle ID via the dev portal? 
- What about adding the random string breaks notifications?
- Is it because the signing and the IPA built have different ID's? If so, could the app be rebuilt with the correct id?

So sorry for the barrage of questions, got carried away. Feel free to ignore any/all questions. No hard feelings.
Thanks!

**Comment by khcrysalis** [comment]
> Would changing the Bundle ID to something random work (eg. com.banana.grape) when signing though the app?

Changing it to something random will make notifications **not work**, it needs to be one found on the App Store. Which is obviously bad for the account if it ever manages to get flagged by Apple.

> Why couldn't I add notif capabilities to the App ID/identifier/Bundle ID via the dev portal?

Not a question to ask here really, recommend you do your own research on how notifications work

> What about adding the random string breaks notifications? Is it because the signing and the IPA built have different ID's? If so, could the app be rebuilt with the correct id?

Adding a random string prevents notifications because... its not the exact identifier found on the App Store

**Comment by jekkkk** [comment]
Ok thanks, I think I got it. Notifications are kind of its own thing that need to be signed onto an App id (not bundle). That notification cert is tied to an app and the server the app uses for said notifications. You need that cert for notifications otherwise bad actors can send malicious notifications through an app (really really bad). This is an issue for sideloading as that notif cert can't be applied as it's not Apple approved and on the app store. Having the id match for the sideloaded app and an official app works as it's just using the cert from the official app but runs the risk of getting flagged.

(mainly for others, I'm sure you knew this)
