### ISSUE TITLE
ability to backup app data

### ISSUE THREAD

**Issue by Cristiandis** [khcrysalis/Feather#14]
like altstore or scarlet

**Comment by khcrysalis** [comment]
Me and others thought about doing this but I found that there's really no use when it comes to these sort of apps.

**Comment by khcrysalis** [comment]
Though if you have more insight on why you would need it, please tell

**Comment by Cristiandis** [comment]
backing up game data or app settings in case of a revoke or reinstall

**Comment by khcrysalis** [comment]
> backing up game data or app settings in case of a revoke or reinstall

Just install over the same bundle identifier, don't delete the app.
