### ISSUE TITLE
Fakesign option?

### ISSUE THREAD

**Issue by vulturul333dfd** [khcrysalis/Feather#140]
I like the app but there is no way to fakesign apps

**Comment by khcrysalis** [comment]
Why would you need a fakesign?

**Comment by vulturul333dfd** [comment]
> Why would you need a fakesign?

There is a way to make fakesign Apps work but i can't find any app that will work with the fakesign option and this is the best app for custom apps

**Comment by khcrysalis** [comment]
Unlikely to happen unless zsign developer adds one, otherwise it seems unlikely that I would add one as it requires too much work and research for something so niche.
