### ISSUE TITLE
[Feature] Version picker

### ISSUE THREAD

**Issue by CreepsoOff** [khcrysalis/Feather#143]
Hello. I'm making this issue to ask for a feature I think is fundamental. Default Altstore repository syntax allows for version history. Would be pretty cool If you could select the version you would like to install, latest by default of course. Got the idea from TrollApps, and I think this would be really convenient for users in case there are some issues for latest version and they want to revert, if the repository is the only distribution channel.

Thanks in advance, attached are some screenshots from the [TrollApps ](https://github.com/TheResonanceTeam/TrollApps) application.

![IMG_9345](https://github.com/user-attachments/assets/a6497108-fd16-4c5a-ab10-7f427a0401a1) 
![IMG_9346](https://github.com/user-attachments/assets/e24e6a61-f74b-4460-9343-075b5a71bbdc)
![IMG_9347](https://github.com/user-attachments/assets/de939d2a-fd80-489e-aff5-09abe52ae603)

**Comment by khcrysalis** [comment]
Feature already implemented since initial release ![image](https://github.com/user-attachments/assets/ed7c35d9-1bf4-4a32-bf15-1c14a89beccd)
