### ISSUE TITLE
Add Option to Expand Repositories Descriptions

### ISSUE THREAD

**Issue by allorionmusic** [khcrysalis/Feather#144]
It would be good to add a way to expand the descriptions for a repository, like this example:
 ![image](https://github.com/user-attachments/assets/3cca27f9-ac2c-4b80-8150-285d06d71005)
A lot of things are missing because the description is long.

**Comment by khcrysalis** [comment]
Go to display options

**Comment by allorionmusic** [comment]
> Go to display options

Alright, so 
Display > Store > Big Description 
for the record. Thanks!

**Comment by allorionmusic** [comment]
> Go to display options

Alright, so 
Display > Store > Big Description 
for the record. Thanks!
