### ISSUE TITLE
Can we change icon when we sideload ?

### ISSUE THREAD

**Issue by NoozPrime** [khcrysalis/Feather#147]
I don't know if it's a bug but I can't change the icon? 
Enhancement
- create an icon for ios 18 dark mode

**Comment by khcrysalis** [comment]
> I don't know if it's a bug but I can't change the icon?

Lack of entitlements.

> create an icon for ios 18 dark mode

Added in https://github.com/khcrysalis/Feather/commit/9a6c604aeeece5b00285971c6023fd4fbe97c147, will be available next release.

**Comment by NoozPrime** [comment]
Is it a bug I can't change the logo of the app?

**Comment by khcrysalis** [comment]
![image](https://github.com/user-attachments/assets/5b6f61c5-795e-40ed-a971-794cf0e8f572)
