### ISSUE TITLE
App install not working

### ISSUE THREAD

**Issue by isibizi** [khcrysalis/Feather#15]
I have the following problem: when I sign and install an app, but this app is already present on the iPhone, the app appears to be installed (the blue dot even appears), but it is not installed over the existing app.

**Comment by khcrysalis** [comment]
[I would recommend you check the bundle identifier](https://github.com/khcrysalis/Feather?tab=readme-ov-file#faq), feather adds a random string by default, which you can turn off, so you can avoid having apple flagging your account.

This is not an issue, rather intended. Also again, you *can* turn it off in settings.

**Comment by isibizi** [comment]
Ok, that means, it isn‘t possible to update an app with ranodomized string, right?

**Comment by khcrysalis** [comment]
No, due to how iOS works. Just remove the randomized string feature in settings or do it manually when signing.

**Comment by isibizi** [comment]
Is it proven that an account can be suspended? I have been using apps with the original string for a long time.

**Comment by apenlol** [comment]
the app identety coul't not be verivied
