### ISSUE TITLE
Ability to change repos around to decide which repos go where in the list

### ISSUE THREAD

**Issue by NoozPrime** [khcrysalis/Feather#151]
I would love that because i want to put main repos on top of the lists.

**Comment by khcrysalis** [comment]
I've decided they should stay in alphabetical order for convenience.

**Comment by yodaluca23** [comment]
> I've decided they should stay in alphabetical order for convenience.

Could there be some sort of options at least? Like Alphabetically, Reverse Alphabetical, Order Imported, Reverse Order Imported?
