### ISSUE TITLE
Reddit Login error

### ISSUE THREAD

**Issue by xENWewho** [khcrysalis/Feather#153]
Hi when Reddit (with tweak redditfilter and the sideloadfix injected) is sideloaded with Feather it give a error that can't sign in, it works with Altstore... any future fix?

**Comment by khcrysalis** [comment]
May be fixed in https://github.com/khcrysalis/Feather/commit/9a6c604aeeece5b00285971c6023fd4fbe97c147? will be available next release.

**Comment by xENWewho** [comment]
Thanks I appreciate all your hard work.

**Comment by xENWewho** [comment]
Can confirm this fix the issue. THANKS A LOT

**Comment by comfortablemilk4454** [comment]
@xENWewho could you help me to get redditfilter working? i am facing issues logging in that happens no matter what method i use to sideload it. i think im experiencing [this issue](https://github.com/level3tjg/RedditFilter/issues/20).
