### ISSUE TITLE
When downloading a Tweaks from a repos it's importing it to your tweaks  choice when signing an app

### ISSUE THREAD

**Issue by NoozPrime** [khcrysalis/Feather#155]
Could be cool but idk if possible

**Comment by khcrysalis** [comment]
Be more clear

**Comment by NoozPrime** [comment]
So like exemple apptester Adblock tweak instead of not allowing me to install it it's gonna install and add it for when i want to sign the app i can add adblock tweak automatically instead of import from outside i can import from repos!
![image](https://github.com/user-attachments/assets/b43372f7-1ece-40e7-a11b-40c366264538)

![image](https://github.com/user-attachments/assets/321bdd8f-63d8-4d90-88f3-375629aceb99)

**Comment by NoozPrime** [comment]
Would see the adblock tweak here and have the choice to click on the + icon that you could add for us to add tweak that we installed 
![image](https://github.com/user-attachments/assets/f94e4cc4-271c-48b1-a2a2-c1f92671b1b6)

**Comment by khcrysalis** [comment]
Not happening as repos themselves don't have tweaks, they store applications.

**Comment by NoozPrime** [comment]
Yes but sometimes they do have some well appreciated the time you readed .

**Comment by khcrysalis** [comment]
If you want that functionality PR it yourself, as I see no point in implementing that sort of thing inside of Feather. Download the tweaks manually and store them on your device.

**Comment by yodaluca23** [comment]
I think they meant like from Cydia/APT sources, and I think this would be a really cool feature. It's like you click the plus for tweaks and it gives you two options from Files or from a APT Source if you choose source then you scroll through your list of sources you've added, can click into one and search through the tweaks or manually scroll and select one.
