### ISSUE TITLE
Regram Tweak Breaks on iOS 18

### ISSUE THREAD

**Issue by xENWewho** [khcrysalis/Feather#158]
Hi i try to install Instagram with Regram tweak on iOS 18 and it breaks, I install same app on iOS 16.5 and works perfectly, I use pyzule and cyan to build the ipa and the correct dylibs... any suggestion or a future update for this? Thanks as always

**Comment by AushevAhmad** [comment]
Are you sure that it's problem with Feather and not tweak itself? I doubt that it's Feathers problem and would suggest you contacting the developer of Regram about this.. My guess is that tweak might be incompatible with iOS 18 which causes breaking.

**Comment by GottaLoveAng** [comment]
there IS an issue with feather and instagram specifically with posts getting cropped weirdly and not showing the full picture. 

but this sounds like op did something wrong with making the ipa, i use regram b14 just fine on 18.2 b1.

**Comment by asdfzxcvbn** [comment]
can you specify what you mean by "breaks" ?

**Comment by xENWewho** [comment]
> Are you sure that it's problem with Feather and not tweak itself? I doubt that it's Feathers problem and would suggest you contacting the developer of Regram about this.. My guess is that tweak might be incompatible with iOS 18 which causes breaking.

Maybe that's why I ask because it work perfect on iOS 16.5 and same ipa doesn't work on iOS 18, maybe is an issue in my end ... any suggestions ? Btw official ipa from dev works and have same dylibs and bundle as mine. Thanks

**Comment by xENWewho** [comment]
> there IS an issue with feather and instagram specifically with posts getting cropped weirdly and not showing the full picture.
> 
> but this sounds like op did something wrong with making the ipa, i use regram b14 just fine on 18.2 b1.

Yes I also face that issue, but doesn't bother me too much, hope there is a fix soon.

**Comment by xENWewho** [comment]
> can you specify what you mean by "breaks" ?

Hi regram settings label not showing correctly, and tweak doesn't function at all. I will check my ipa to see if the problem is at my end that maybe the case. Any suggestion I will appreciated. Thanks

**Comment by GottaLoveAng** [comment]
yea that is on your end, i gave you instructions on the regram discord a few days ago coincidentally enough. but no, its not a feather issue. you likely didnt include the bundle like needed.

**Comment by xENWewho** [comment]
> yea that is on your end, i gave you instructions on the regram discord a few days ago coincidentally enough. but no, its not a feather issue. you likely didnt include the bundle like needed.

yes I've try everything but no luck on fixing the issue, rare that they work on other iOS , but thanks anyways.

**Comment by asdfzxcvbn** [comment]
> Hi regram settings label not showing correctly, and tweak doesn't function at all

yeah, definitely missing bundle. you need to inject Regram.bundle and WatusiTools.bundle
