### ISSUE TITLE
App not installing anything

### ISSUE THREAD

**Issue by KarmaBeast** [khcrysalis/Feather#159]
I'm trying to install the latest uYouEnhanced ipa. Unfortunately I get a white page every time, and other apps or installing apps from repos also doesn't work. I have disabled all safari extensions and it still doesn't work and gets stuck in this white screen:

![image](https://github.com/user-attachments/assets/e78bda6a-8a39-49cd-811b-5016ed23cb7f)

Using the latest version of feather released 25 days ago. iOS 18.1 on iPhone 14 PM.

**Comment by khcrysalis** [comment]
Refer to https://github.com/khcrysalis/Feather/issues/108
