### ISSUE TITLE
Selecting different app icon doesn't work

### ISSUE THREAD

**Issue by KarmaBeast** [khcrysalis/Feather#160]
Apart from the fact that the app is not installing any ipa, there's also a bug I found. Choosing another app icon doesn't work. Cannot select any.

![image](https://github.com/user-attachments/assets/f7b6741d-e276-4918-aea2-0d0d4c10bedc)

**Comment by khcrysalis** [comment]
Entitlement issue, unrelated to feather itself.

**Comment by Ichicoro** [comment]
> Entitlement issue, unrelated to feather itself.

Could you elaborate? The wiki doesn't explain what this issue might be and how it could be fixed

**Comment by khcrysalis** [comment]
> Could you elaborate? The wiki doesn't explain what this issue might be and how it could be fixed


It's exactly what I said, signing applications with for example a Kravasign certificate will make you unable to change application icons as the entitlements needed from your certificate don't let it change.

The fix is to get a development certificate or upload it to the appstore

**Comment by LifeDreamer24** [comment]
> > Could you elaborate? The wiki doesn't explain what this issue might be and how it could be fixed
> 
> It's exactly what I said, signing applications with for example a Kravasign certificate will make you unable to change application icons as the entitlements needed from your certificate don't let it change.
> 
> The fix is to get a development certificate or upload it to the appstore

I have paid a development certificate from apple. Could you provide the information on which changes/additions are needed for this to work? I will be glad to donate for your help :)
