### ISSUE TITLE
New app icons?:]

### ISSUE THREAD

**Issue by BLUSlushyy** [khcrysalis/Feather#162]
I made one actually for this month if anyone wants it would be cool if you add this one onto the app??I wanna make custom themes for it honestly just cause why not![image](https://github.com/user-attachments/assets/201f98bd-c863-4f80-adbe-9f1f0704204b)🥹

**Comment by khcrysalis** [comment]
I can add icons if you make a pull request, but I only take icons that have at least a bit of effort put into them and not a simple hue change :)
