### ISSUE TITLE
Language fix

### ISSUE THREAD

**Issue by D1mar0n** [khcrysalis/Feather#163]
Hello! Big. Thank you for the work done. After the update, many languages disappeared, there are only 4 left... In addition, maybe there is an opportunity to add updates to the application? Now if you install the new version, it does not overwrite the old version and all the settings have to be done again... Thank you in advance for your answer.

**Comment by khcrysalis** [comment]
> After the update, many languages disappeared, there are only 4 left... 

Thats the languages still exist in the project, I just removed them from the build as I want them to be more complete before I ship them.

> Now if you install the new version, it does not overwrite the old version and all the settings have to be done again... 

Thats because you signed it with a different bundle identifier. Also, if you use the same bundleidentifier it will not work so you will need to use an external signing software for that :)

**Comment by D1mar0n** [comment]
Thank you very much for your answer. For me, version 1.0.5 on iOS 18.2 works without problems, until then I will refrain from updating, otherwise I will have to integrate my certificate again and wait for the Russian language to appear in the interface.

Do you have any plans to add the ability to integrate ".dylib"?

**Comment by khcrysalis** [comment]
Theres really no issues though and I would recommend updating, also be aware I dont take bug reports from older versions. Also, importing dylibs has been a thing since the beginning.

**Comment by D1mar0n** [comment]
"Also, importing dylibs has been a thing since the beginning." - I know, I'm not complaining in any way. Just asking if this is even possible and if we should expect a future update for this feature. Thank you very much again for your application and for your answers. Have a nice weekend.

**Comment by khcrysalis** [comment]
Why would there be an update if it already exists?

**Comment by khcrysalis** [comment]
![image](https://github.com/user-attachments/assets/3175d9e6-efee-4be5-8f43-2558b073093e)

**Comment by D1mar0n** [comment]
Sorry, I'm staying on version 1.0.5 for now - it only has the ability to remove "dylib". I didn't know that the new version already has this feature. Later I will update the version and be sure to test this feature. Thank you!
На Сб.02.11.2024 6:25:19, samara ***@***.***> написал(а):
Why would there be an update if it already exists?

**Comment by khcrysalis** [comment]
Why would that feature be removed..?? That wouldn't make sense.
