### ISSUE TITLE
Cant install App ipa's

### ISSUE THREAD

**Issue by Jackolix** [khcrysalis/Feather#174]
I cant install Apps with feather. 

I can import ipa's and sign them but not install them. 
It asks me to if i want to: **"install _App_ from app.localhost.direct"** but when i accept i just get a message: **"_App_ cannot be installed. Try again later."**

I could install winston, but not YTLitePlus, uyou+ or Esign.

**Comment by hzozo** [comment]
I started having the same issue starting this morning. Couldn’t even install apps I have signed and installed already.

**Comment by AushevAhmad** [comment]
Same here...

**Comment by Hazexx143** [comment]
Same issue still no fix ?????

**Comment by TrashPandaIlm** [comment]
https://github.com/Upinel/localhost.direct/issues/18

Looks like their cert got revoked

**Comment by khcrysalis** [comment]
that makes complete sense on why its not working, so for now use the online-installing 'methods'.

**Comment by Upinel** [comment]
Hi, I am the lead of [localhost.direct](https://github.com/Upinel/localhost.direct) project, please make sure the key never should able to be view publicly and it should always password protected. The cert bundle is zipped and password protected with a reason. Thanks.
Shouldn't: https://github.com/khcrysalis/Feather/blob/main/Shared/Server/localhost.direct.key

**Comment by khcrysalis** [comment]
Contacted :)

**Comment by khcrysalis** [comment]
@Upinel hey just a reminder I sent an email
