### ISSUE TITLE
Bring Back PPQ Detection

### ISSUE THREAD

**Issue by dylans509** [khcrysalis/Feather#178]
Can you bring back PPQ Detection to the next Feather Release?![image](https://github.com/user-attachments/assets/84c9ada3-08d2-4259-b6b5-7a6d29654ac8)

**Comment by khcrysalis** [comment]
It already exists in signing options, you have to learn how to check settings.

**Comment by dylans509** [comment]
Is it the Enable Protection?Sent from my iPhoneOn Nov 16, 2024, at 1:58 PM, samara ***@***.***> wrote:﻿
Closed #178 as completed.

**Comment by khcrysalis** [comment]
Yes.
