### ISSUE TITLE
[request] add the information part of the app in repos

### ISSUE THREAD

**Issue by fredystar200** [khcrysalis/Feather#179]
Thank you very much for this app, I wanted to know if it's possible to add the information part of the apps in the repos part so when you click an app you have the size and the last update date of the app

Thanks

**Comment by fredystar200** [comment]
same as #172

**Comment by khcrysalis** [comment]
avoid making duplicates

**Comment by fredystar200** [comment]
i did the same request without knowing there was already one existing
