### ISSUE TITLE
Stuck at "ready to install" 

### ISSUE THREAD

**Issue by jb-ctrl** [khcrysalis/Feather#186]
I just needed to install feather  1.3 again because it was not working anymore. Now when i want to Install apps . It always stucks at "ready to install" Im on Iphone 15 Pro iOS 18.1

![grafik](https://github.com/user-attachments/assets/494ca306-d01a-47f6-bb1a-1f2bdbad2a4e)

**Comment by khcrysalis** [comment]
this bug happens due to missing entitlements provided by the certificate, regarding it not working on latest its either the same or related to this issue [here](https://github.com/khcrysalis/Feather/issues/182)
