### ISSUE TITLE
Remove Provisioning File option is in reverse?!

### ISSUE THREAD

**Issue by sevenpastzeero** [khcrysalis/Feather#188]
I just noticed that if the "Remove Provisioning File" option is _on_ in the signing properties window, the "embedded.mobileprovision" file is still presented. If the option is _off_ then the file is removed. Is that intended? I thought it was supposed to be the other way around.

I am using the latest version, v1.1.3

**Comment by khcrysalis** [comment]
I think that's because of me messing up the localization context when implementing the signing options
