### ISSUE TITLE
feat: url scheme paths

### ISSUE THREAD

**Issue by castdrian** [khcrysalis/Feather#193]
It'd be great if we'd had a couple of paths for the url scheme to call:

```
feather://repository?q=https://repo.json
feather://install?q=https://file.ipa
```

**Comment by khcrysalis** [comment]
https://github.com/khcrysalis/Feather/blob/main/iOS/Delegates/AppDelegate.swift#L71-L95

There's already one for repositories, for ipas I thought importing to the app with the sharesheet or through download page would be enough.

**Comment by castdrian** [comment]
lovely, very nice example url you used as well 🥹
the install one was just something that came to mind for like on-demand testing, guess I kinda got entraced by trollstore lite there
