### ISSUE TITLE
Feather won't let me add a repo

### ISSUE THREAD

**Issue by dylans509** [khcrysalis/Feather#195]
Feather does not let me add the repo below but SideStore and Scarlet did. I tried to paste the link and import resource but it does not add it to my sources tab 

(repo link censored due to code of conduct)

**Comment by GottaLoveAng** [comment]
the repo has been down for a while now. it wont let you add it because there's no information to be received by feather. 

i dont know why it worked with sidestore and scarlet, perhaps you already had it added and it was cached? either way it wouldn't let you download apps from the repo anyways.

**Comment by dylans509** [comment]
I just added the repo and scarlet did let me install an app of that repo Sent from my iPhoneOn Nov 23, 2024, at 12:17 AM, ang ***@***.***> wrote:﻿
the repo has been down for a while now. it wont let you add it because there's no information to be received by feather.
i dont know why it worked with sidestore and scarlet, perhaps you already had it added and it was cached? either way it wouldn't let you download apps from the repo anyways.

**Comment by khcrysalis** [comment]
it works in my machine

**Comment by dylans509** [comment]
How did u add it?Sent from my iPhoneOn Nov 23, 2024, at 1:19 AM, samara ***@***.***> wrote:﻿
it works on my machine

**Comment by khcrysalis** [comment]
Adding it like any other repository

**Comment by dylans509** [comment]
Mine it dosent let me add itSent from my iPhoneOn Nov 23, 2024, at 11:33 AM, samara ***@***.***> wrote:﻿
Adding it like any other repository

**Comment by khcrysalis** [comment]
Sorry but I've already confirmed it works using the latest version of feature, don't know what to tell you, you must be doing something wrong on your own.
