### ISSUE TITLE
Allow File Browser not working

### ISSUE THREAD

**Issue by hellodrsoul** [khcrysalis/Feather#201]
Sideloaded apps are not able to pick a file from files.app. The file browser shows up but you are unable to select a file. Clicking a file does nothing. 

iPhone 15 pro max
iOS 18.1.1
Cert: Paid cert (from eth4dmin)
Feather version 1.1.3
Bundle identifier: Default
Minimum app version: Default
Signing method: Online
Allow file browsing option set to “on” under advanced (screenshot attached)
![IMG_7226](https://github.com/user-attachments/assets/9b62a8b2-9373-4a86-9e62-6a57c61cf89f)

**Comment by GottaLoveAng** [comment]
the option is for browsing the apps files _from the files app_. it is not for giving the app entitlements needed for accessing files. (Files > On my iPhone > [Insert App Folder Here])

As for why you cannot select files using sideloaded apps, it's an entitlement issue unrelated to feather.

**Comment by hellodrsoul** [comment]
LiveContainer has an option to fix file browser under individual app settings. Was hoping for similar. But I understand LiveContainer uses cert from SideStore which is different than the paid distribution cert I am using now.
