### ISSUE TITLE
Feather beta

### ISSUE THREAD

**Issue by dylans509** [khcrysalis/Feather#206]
So why are there no apps on the "secret repo" of the Feather Beta![image](https://github.com/user-attachments/assets/90dc0c0b-4819-458e-9fbb-38e5d448f0c6)

**Comment by khcrysalis** [comment]
The secret repo is for the beta :)

**Comment by dylans509** [comment]
So there won’t be any 3rd party apps plus it looks exactly the same as the public app buildSent from my iPhoneOn Nov 30, 2024, at 12:33 AM, samara ***@***.***> wrote:﻿
Closed #206 as completed.

**Comment by khcrysalis** [comment]
It was never implied there were third party apps on said repo, you were always paying for beta builds. 

And no, its not exactly as new builds get uploaded every commit which is bleeding edge
