### ISSUE TITLE
bug: crash when attempting re-sign when no certificate selected

### ISSUE THREAD

**Issue by castdrian** [khcrysalis/Feather#211]

**Comment by khcrysalis** [comment]
I presume this happens when you try to remove your certificate data

**Comment by xudondon888** [comment]
The formats supported by software sources are not friendly, such as php or this software source.https://app.appds.cn/appstore

**Comment by xudondon888** [comment]
> 

I hope this app can hide this link or give the software source its own name![image](https://github.com/user-attachments/assets/191198a2-faa6-4bc6-af4a-967dd64e519c)  can become elegant

**Comment by xudondon888** [comment]
> I presume this happens when you try to remove your certificate data

![image](https://github.com/user-attachments/assets/02ef9cfa-56f3-42e6-9aa4-b8c65a49c533)
I hope this App can become more elegant, remove this link, and rename my own software source and change the icon to support the format of the software source more widely, such as this software source, I can't add or other countries' software sources.

Https://app.appds.cn/appstore

**Comment by xudondon888** [comment]
> I presume this happens when you try to remove your certificate data

![image](https://github.com/user-attachments/assets/c8bbb400-eb1f-4488-b1aa-418f905a474d)
The great author hopes that you can partially optimize this software, that is, it cannot display his upload time and update time, which plays a partial role in downloading useful apps.

**Comment by khcrysalis** [comment]
@xudondon888 When suggesting changes or requesting features, its best to create a new issue and not try to fill up an existing one unrelated to what you're trying to say
