### ISSUE TITLE
Create another version of feather

### ISSUE THREAD

**Issue by dylans509** [khcrysalis/Feather#214]
Could you give us the feather source code so we can make an app of it with our design but use swiftUI instead of UIKit?

**Comment by castdrian** [comment]
uh, this repository _is_ the source code

**Comment by khcrysalis** [comment]
> Could you give us the feather source code so we can make an app of it with our design but use swiftUI instead of UIKit?

https://github.com/khcrysalis/Feather

**Comment by dylans509** [comment]
We want to make a version of feather but with our own things like UI Design and new features Sent from my iPhoneOn Dec 3, 2024, at 10:27 PM, Adrian Castro ***@***.***> wrote:﻿
Closed #214 as not planned.

**Comment by khcrysalis** [comment]
Feather is open source and allows you to fork and make modifications, granted you follow the rules the license provides.
I.e. making it open source, giving proper credit, etc.
