### ISSUE TITLE
I can t  download the Feather applications

### ISSUE THREAD

**Issue by popcorn2024ok** [khcrysalis/Feather#217]
![IMG_0127](https://github.com/user-attachments/assets/1b42617e-a7e8-41ac-b815-54960b806bfa)

I can t download the Feather applications I get this problem and error version 1.1.3

**Comment by AushevAhmad** [comment]
Enable 'Online Install Method'. Settings -> Server Options.

**Comment by popcorn2024ok** [comment]
> Enable 'Online Install Method'. Settings -> Server Options.

![IMG_0129](https://github.com/user-attachments/assets/1c9ad5ce-9ecc-407a-9987-efbba9e2e5d0)

stays for not downloading in Feather

**Comment by popcorn2024ok** [comment]
> Enable 'Online Install Method'. Settings -> Server Options.

![IMG_0130](https://github.com/user-attachments/assets/6d0c8b28-f879-4785-ac29-27701858b094)

I know that in white it doesn't download, I know that I do that too

**Comment by castdrian** [comment]
duplicate of #203
