### ISSUE TITLE
Feature Request: No certificate mode

### ISSUE THREAD

**Issue by zeroxoneafour** [khcrysalis/Feather#219]
Option to sign without certificate. I use this option with ESign to modify IPAs and install them through LiveContainer.

**Comment by castdrian** [comment]
That’s feels out of scope, if you want an ipa patcher use cyan

**Comment by zeroxoneafour** [comment]
Is cyan only available as a command line tool? I dont have a jailbroken device where this would be convenient for me.

**Comment by castdrian** [comment]
closing this as it's out of scope and other tools exist for this purpose
