### ISSUE TITLE
Unable to install "App Name" 

### ISSUE THREAD

**Issue by alaa-hany-elsaid** [khcrysalis/Feather#224]
### Version

All versions 

### Start going into detail..

I have update ssl with a custom domain that bind to 127.0.0.1 iappcloud.alaahnay.name
but still get unable to install 
i ping the server and all endpoints are working good 
image , plist and ipa 
but failed to be installed

![image](https://github.com/user-attachments/assets/252068b6-4c45-4152-aeec-5fa2e31a1ece)

**Comment by castdrian** [comment]
if you modify files included in the project and it breaks that's your own responsibility
