### ISSUE TITLE
Noob question - cannot find a way to disable PPQCheck

### ISSUE THREAD

**Issue by GrPK** [khcrysalis/Feather#225]
### Version

18.3

### Start going into detail..

![image](https://github.com/user-attachments/assets/c341ecee-68bf-473e-8847-db128c55f4d3)
Hello, maybe it's a noob question and a easy one, but I cannot find a way to disable the PPQCheck whenever I try to sign apps so that I can have notification. As I showed in the uploaded screenshot, the check is always there, even if I toggled off the "Protection" setting in Signing Options. I checked every menu, but I don't find anything related to PPQCheck...

**Comment by khcrysalis** [comment]
Your certificate will always contain ppqcheck, you cannot turn it off unless you own the account associated with the certificate and request an offline certificate from Apple.

From your screenshot provided, it seems you have already turned it off as theres no random string attached to the bundle identifier.
