### ISSUE TITLE
Error when opening All Repositories page

### ISSUE THREAD

**Issue by dylans509** [khcrysalis/Feather#226]
### Version

iOS 18.3

### Start going into detail..

I keep getting this error when opening the All Repositories page
![IMG_0828](https://github.com/user-attachments/assets/46ea50d4-21a1-46bb-91d7-ab153f86f679)

**Comment by khcrysalis** [comment]
One of your repositories are invalid and don't have the necessary keys for them to display in feather

**Comment by dylans509** [comment]
Also is it possible for us to have the ability to reorder our sources in the next update?Sent from my iPhoneOn Dec 22, 2024, at 12:46 PM, samara ***@***.***> wrote:﻿
Closed #226 as completed.
