### ISSUE TITLE
Feature to Download and Sign .IPA Files Using Personal Data Over LTE/5G

### ISSUE THREAD

**Issue by NoozPrime** [khcrysalis/Feather#229]
### Feature Description

Add a feature that allows users to download .ipa files and sign them with their personal data directly within the app. This feature should support the ability to perform these actions over an LTE or 5G network, ensuring flexibility and convenience for users who are not on Wi-Fi.

### Start going into detail..

I think it should also include:
	•	An option to toggle between Wi-Fi only or cellular data (LTE/5G) for downloading .ipa files.
	•	A streamlined process for signing .ipa files using personal developer credentials directly in the app.
	•	Clear indications of download progress and signing status.

This feature would greatly enhance usability by enabling on-the-go signing and downloading, making the app more versatile for users who rely on cellular networks.

**Comment by khcrysalis** [comment]
Thanks for the suggestion, unfortunately if you've seen recent issues theres been regarding the ssl certificate you will know it's been an ongoing problem during this month.

Also, a toggle between using mobile data and wifi is useless, turn it off yourself within the control center.

The download progress has also been already requested here https://github.com/khcrysalis/Feather/issues/113

**Comment by NoozPrime** [comment]
Merry Christmas eve !
