### ISSUE TITLE
Certificate display name 

### ISSUE THREAD

**Issue by Ketarmin** [khcrysalis/Feather#23]
Hey, I have a request. 

Can you change standard display Name which get shown for the Certificate, please?

right now Feathers displays the „App ID Name“ of a Cert as the certificate name but I think it’s better if Feather uses the „Team Name“ instead because in my case my certificate provider use the same „App ID Name“ through all his certificates which makes it really hard to differentiate between different certificates.

![IMG_5893](https://github.com/user-attachments/assets/bc13e928-a6e9-42bb-a1a6-82dd91d5e2c8)

![Enlight14](https://github.com/user-attachments/assets/49b59437-e692-4b63-a8a3-c8c4014c9f73)

and can you add the option to open certificates like in Esign, please?

![Enlight13](https://github.com/user-attachments/assets/ac5a7c87-59a9-4105-80ad-c090ff16c4e5)

**Comment by khcrysalis** [comment]
For the first point, I really only did it to have privacy for people taking screenshots however I can add an option to display team-name instead.

For the second, I don't really see a use-case for being able to fully expand the certificate as you really would only be using the certificate for sideloading and nothing else.

**Comment by khcrysalis** [comment]
Though I don't have a problem with adding that functionality as I have code to parse the mobileprovision already

**Comment by Ketarmin** [comment]
> For the first point, I really only did it to have privacy for people taking screenshots however I can add an option to display team-name instead.

That would be great if add this option.

> For the second, I don't really see a use-case for being able to fully expand the certificate as you really would only be using the certificate for sideloading and nothing else.

Yea, true but it’s better to have the possibility then to need it someday

**Comment by Ketarmin** [comment]
Something else, can you tint the „days left“ green to visually highlight it that the cert is not revoked, please?
![IMG_5893](https://github.com/user-attachments/assets/e6ce93ce-403e-4a17-847d-d4f85d271630)

**Comment by khcrysalis** [comment]
I sadly have no code to check if the certificate is revoked, maybe sometime later though

**Comment by khcrysalis** [comment]
https://github.com/khcrysalis/Feather/releases/tag/v1.0.1 has been released, with a feature for changing the display name to team name!
