### ISSUE TITLE
Documentation needed for custom install servers

### ISSUE THREAD

**Issue by ramirocantu** [khcrysalis/Feather#231]
### Feature Description

Instructions needed for running custom plist servers and implementing https.

### Start going into detail..

For users on iOS 18+ who need to use a online install method and are not comfortable sending information to an unknown server/want to use their own. It is very confusing to figure out the process of running your own server, i realize that the code to run your own server is at https://github.com/nekohaxx/plistserver , but that project offers no documentation or logging and runs on http-only mode so I've got to figure out how to run it with https. Would appreciate any advice on running my own plist server. Thanks!

**Comment by ramirocantu** [comment]
Sorry unknown to me, we have to disable "Not secure connection warning" in safari to get the official install server to work but I've still havent been able to make the custom one work.

**Comment by castdrian** [comment]
Looking at their implementation it is 60 lines long, it's not really anything I'd fault the developer for not documenting as anyone can just read it, as for this repo, I don't think it is Feather's responsibility to write documentation for an optional dependency but samara may or may not agree

**Comment by ramirocantu** [comment]
As to what is confusing. I am not confused about "cargo run". I am confused on troubleshooting. Both plistserver and feather not having docs or log messages make this difficult. I know that my server is addressed correctly due to macOS prompting me to allow connections when I attempted to install from feather - yet apps don't install after clicking install on the iTunes dialog.

If you've managed to make it work please let us know.

I understand that it is nobodies responsibility to maintain or document open source software - it is volunteer work done by passionate people.

I hope using custom servers are not viewed as an optional dependency especially since it seems that the spirit of feather is to collect no telemetry and be as on-device as possible. Thanks!

**Comment by castdrian** [comment]
I mean debugging is kind of up to you, check if your plist payload is returned properly, I'm quite inclined to closing this as troubleshooting plistserver is something that is not currently anything in relation to feather itself

if this was an org and we would maintain a fork of it then I'd entirely agree with the proposition of maintaining documentation, for now I'll close this however unless samara interjects and says "hey let's write up some docs on setting up plistserver for end users"
