### ISSUE TITLE
Unable to Install Issues

### ISSUE THREAD

**Issue by atellies** [khcrysalis/Feather#29]
When attempting to sign with certs with the correct Entitlements for Fortnite or even in general for some reason Feather will always spit out “Unable to Install” errors and the app does not install correctly yet it works on anything else like ESign. Find example IPA here 
: <redacted>

none of the a Fortnite IPAs work

**Comment by khcrysalis** [comment]
Hey dont use this repository to link your pirated content, thank you!

**Comment by khcrysalis** [comment]
It worked for me when I tried originally, though it highly depends on the certificate you have tried.

**Comment by khcrysalis** [comment]
The technologies used in feather make sure that everything is correct when installing, if iOS can't accept it then theres a valid reason why it can't.

I would need some further insight on it really or else I can't figure out whats going on.

**Comment by atellies** [comment]
I can provide you with a device log later if possible
