### ISSUE TITLE
App description

### ISSUE THREAD

**Issue by Hecbert** [khcrysalis/Feather#3]
It would be more helpful to see the actual app description and release date in external sources, rather than just displaying "An awesome application."

And if possible, show all apps of every source instead of having to pick one source.

**Comment by khcrysalis** [comment]
"An awesome application." is a short description of the application, if theres no short description provided it will default to that. Not all repos have it, however the ones that are featured on altstore do (as they generally follow guidelines that altstore provides).

I could have an option to change it, and maybe display the version as well, I will see how good it looks

**Comment by Hecbert** [comment]
I asked because popular repos like Apptesters and SwaggyP360000 display “An awesome application.” instead of the apps description.

**Comment by khcrysalis** [comment]
I will consider those, but its merely up to them to update to use new standards. Also, please avoid mentioning stuff that can be related to pirating in issues.

**Comment by khcrysalis** [comment]
Gonna keep this issue open until I have a decent way of displaying it better :)

**Comment by khcrysalis** [comment]
https://github.com/khcrysalis/Feather/releases/tag/v1.0.1 has released with a customization option for this!
