### ISSUE TITLE
Cannot add a repo if it doesn't start with https://

### ISSUE THREAD

**Issue by imbigdilly** [khcrysalis/Feather#39]
You can't add a repo if it doesn't start with https://

So for example, if you wanted to add **repo.starfiles.co**

It will display an error message.
You would have to enter **https://repo.starfiles.co** for it to work, with the https added.

What should happen is that this gets added onto the link automatically if it's not there already

**Comment by AushevAhmad** [comment]
:husk:

**Comment by khcrysalis** [comment]
> You can't add a repo if it doesn't start with https://

Intended, must be a valid https link!

**Comment by imbigdilly** [comment]
> > You can't add a repo if it doesn't start with https://
> 
> 
> 
> Intended, must be a valid https link!

It should just auto add the https though, the link is valid and every web browser will accept a link just fine without the https -- if it's missing, it gets added on by the browser and you don't even have to think about it. It's 2024, we don't have to type www. or https:// into links anymore, it's just done automatically.
