### ISSUE TITLE
Feather unable to update itself

### ISSUE THREAD

**Issue by ccsasuke** [khcrysalis/Feather#42]
Hi,

I'm running Feather 1.0. After signing Feather 1.0.1, it fails to install the newer version of the app itself. It installs other IPAs without issues. Is it just me or is there a bug regarding updating the Feather app itself?
Thank you.

**Comment by khcrysalis** [comment]
Well its because youre trying to feed the ipa while ios is installing over itself, so it could cause issues with the same bundleidentifier.

Nothing i can do about it really, just use a different signer to over feather :(
