### ISSUE TITLE
Repo Source support for sidestore

### ISSUE THREAD

**Issue by I-794** [khcrysalis/Feather#43]
Is it possible to create a source repo made for SideStore?

**Comment by khcrysalis** [comment]
Not sure what you mean, please explain.

**Comment by I-794** [comment]
> Not sure what you mean, please explain.

Basically like a altstore repo link but for sidestore

See here https://github.com/SideStore/Community-Source

**Comment by imbigdilly** [comment]
they are supported, but you need to add the full link (with the https)

**Comment by I-794** [comment]
Oh ok!

**Comment by I-794** [comment]
> they are supported, but you need to add the full link (with the https)

I did but it didn't work ![image](https://github.com/user-attachments/assets/1b2e42f2-8423-44f9-903b-279298484552)

**Comment by imbigdilly** [comment]
Why are you trying to add the repo to sidestore, you should add it to feather

**Comment by I-794** [comment]
Im trying to install it through sidestore

**Comment by imbigdilly** [comment]
you don't add it as a repo

what you should do is download the ipa, and then import that into sidestore

but doing this causes the app to have a 7 day limit like other sidestore apps

so, you need to download the app again, but this time from within feather

import your dev certs to feather, then go to the sources tap, and download and sign a new version of feather. install and delete the old version.

**Comment by I-794** [comment]
Ah ok! I get it! Thank you for explaining!
