### ISSUE TITLE
[Enhancement] Combine Search Features and Improve App Deletion Options for Better Storage Management

### ISSUE THREAD

**Issue by Am1nCmd** [khcrysalis/Feather#46]
I suggest combining the search functionality into a single "Search" tab, which would allow users to search for apps across all repositories that have been added.

Example on Sileo, Zebra, Cydia or similar to them

For the Remove or Delete feature, I propose adding an option in the "Settings" under the "Advanced" tab, specifically within the "Reset" section. This option would be labeled "Delete All IPA Library," enabling users to remove all downloaded and signed apps at once, rather than deleting them individually from the Library tab.

Alternatively, consider adding options in the Settings to automatically enable "Delete Downloaded Apps After Signing" or "Remove Signed Apps After Installation." 

These features would help in managing storage more effectively, especially on devices with limited storage capacity.

**Comment by AushevAhmad** [comment]
> Alternatively, consider adding options in the Settings to automatically enable "Delete Downloaded Apps After Signing" or "Remove Signed Apps After Installation."

sounds better imo

**Comment by khcrysalis** [comment]
Good suggestions! Honestly its quite difficult in my opinion to add search options when it comes to altstore repos and repos in general

I've added a search bar at the top of the sources section which already allows you to search through every single repo, but apparently thats not enough

**Comment by khcrysalis** [comment]
The stuff for better management is kinda iffy to me, ive tried to set a standard on you being able to delete them manually but adding something to batch delete doesnt sound too bad

**Comment by khcrysalis** [comment]
Also, keep this open so I can keep track of features people want

**Comment by Am1nCmd** [comment]
> > Alternatively, consider adding options in the Settings to automatically enable "Delete Downloaded Apps After Signing" or "Remove Signed Apps After Installation."
> 
> 
> 
> sounds better imo

Yup, it cost a lot of storage when importing IPA, and double it when signed the IPA

![image](https://github.com/user-attachments/assets/ceeb3b2c-32eb-4e4a-992b-dbd9c37e92a7)

Even though this IPA (screenshot) file application is only about 12.5 MB.

**Comment by Spritzerland** [comment]
i believe this should be added also

**Comment by khcrysalis** [comment]
Added some of these in https://github.com/khcrysalis/Feather/commit/9a6c604aeeece5b00285971c6023fd4fbe97c147, will be available next release.
