### ISSUE TITLE
[Enhancement] Add option to only show latest versions when searching & a page that shows newly added apps from all repos

### ISSUE THREAD

**Issue by xologram** [khcrysalis/Feather#48]
Would it be possible to add a toggle in settings that would only show latest versions of the app from each repo when searching? Right now it shows ALL versions which can sometimes be too much. It is useful to have as an option, that's where the toggle comes. 

Also, a dedicated page which shows latest apps added to all repos would be a nice addition!

**Comment by khcrysalis** [comment]
This only happens because those repos dont comply to altstore 2.0 standards, so its the repositories fault they list every single version.

When it comes to repos that do comply, such as feather, altstore, UTM, etc. You described what feather can already do! To access more versions you can hold on the download button for those 2.0 compliant repos

**Comment by khcrysalis** [comment]
![image](https://github.com/user-attachments/assets/07fac913-0b12-4d81-8637-f877846ed4b8)

**Comment by xologram** [comment]
yeah this is perfect! good to know. too bad most tweaked repos out there do it wrongly. i don’t suppose you could hack it into feather to do the right thing for old repos? it would improve the experience a lot!

**Comment by khcrysalis** [comment]
> yeah this is perfect! good to know. too bad most tweaked repos out there do it wrongly. i don’t suppose you could hack it into feather to do the right thing for old repos? it would improve the experience a lot!

I can try, though I would need a way of identifying the apps properly like with a bundleidentifier (hopefully) listed in the repository

**Comment by xologram** [comment]
either way i love the app, much more sleek than all others i've tried. a couple of other enhancements i could see is already mentioned page with latest apps across all repos, an option to automatically sign and install (or just install after sign). 

thank you for making this and making it open source!

**Comment by icenoir** [comment]
> either way i love the app, much more sleek than all others i've tried. a couple of other enhancements i could see is already mentioned page with latest apps across all repos, an option to automatically sign and install (or just install after sign). 
> 
> 
> 
> thank you for making this and making it open source!  

on ESign for example I think they can filter for release/publish date on the repo and there is often a description with the versioning like the image attached ![image](https://github.com/user-attachments/assets/4e695778-d3db-429e-affb-9748c8a4cadb)

**Comment by khcrysalis** [comment]
Added in https://github.com/khcrysalis/Feather/releases/tag/v1.0.2
