### ISSUE TITLE
Great app; how I think it could be better

### ISSUE THREAD

**Issue by mastermindZACH** [khcrysalis/Feather#5]
This is great. I'm working on transferring my repos from esign. It would be great if you made it possible to accept that format, instead of just the URLs. Additionally, it might be wise to add a page like esign has with all the apps from your repos, instead of having to search for every app.

**Comment by khcrysalis** [comment]
What format are you specifically referring to?

Also I can add an all apps section sure, however I would like to ask what would be the point of this if you can search them anyway?

**Comment by mastermindZACH** [comment]
This is what I was referring to:

source[5GHxhb1U7Lc+lp5guDdEYtGgalJJ2LYZAa76]

However, now I am trying to just add the links, and when I hit add source
it’s not working. I assume this is a bug?

**Comment by khcrysalis** [comment]
If its typed incorrectly it can just not do anything yeah, or even just an invalid link

If its a valid link but its a bad repo it will give an error

I should do something about it

**Comment by khcrysalis** [comment]
> source[5GHxhb1U7Lc+lp5guDdEYtGgalJJ2LYZAa76]

This just seems like a way for esign to export repositories in your clipboard no?

**Comment by mastermindZACH** [comment]
Correct

**Comment by khcrysalis** [comment]
Esign "repositories" here only mean the export feature it has it seems.

I can add an all way to import batch sources, though I would need to consider stuff like maplesign too

I will need to look into how they're encoded

**Comment by mastermindZACH** [comment]
This is the problem I was running into. Any fix? I will try reinstalling. https://github.com/user-attachments/assets/e3b9b422-9937-476d-958c-95ae3acea524

**Comment by khcrysalis** [comment]
<img width="283" alt="image" src="https://github.com/user-attachments/assets/e136a264-2f2d-4800-9df0-b47f69709193">

you're not typing in the correct url.

**Comment by mastermindZACH** [comment]
Interesting, works fine on my esign, I copied it from there. This is just
an example.

**Comment by khcrysalis** [comment]
>  works fine on my esign

**you see esigns copy option also copies the title which is kinda bad design**, feather ONLY accepts a valid URL.

adding junk like the title in front of the url will not work. it just needs to be a url.

**Comment by mastermindZACH** [comment]
Ha! Not sure how I missed that. Thank you

**Comment by khcrysalis** [comment]
Well glad its working!
