### ISSUE TITLE
Add new localization strings

### ISSUE THREAD

**Issue by AushevAhmad** [khcrysalis/Feather#56]
Title, duh

**Comment by khcrysalis** [comment]
Show images please.

**Comment by AushevAhmad** [comment]
![IMG_0060](https://github.com/user-attachments/assets/ac3f1b40-cf0f-4e54-bd70-b026d3fe947f)
![IMG_0061](https://github.com/user-attachments/assets/24e4438f-5d91-4f4e-88a6-2586bea267b9)
![IMG_0062](https://github.com/user-attachments/assets/d13e4bec-1fb0-44eb-8e45-9058a8e2caa1)
These are just a few examples.. There is more stuff of course

**Comment by khcrysalis** [comment]
Added more in newest version
