### ISSUE TITLE
Is it possible to make it work with the ESign DNS

### ISSUE THREAD

**Issue by Leilan1000** [khcrysalis/Feather#57]
The only reason I’ve been using ESign is because it has anti-revoke and I don’t have to worry about them expiring so if you could make it possible to do that I’m asking because I love the Y, but I can’t buy a certificate

**Comment by viro2** [comment]
It does work, see the issue I posted 2 before yours, you just whitelist the url I provided and can download a p12 cert from applep12.com Tele or I can send you one if needed

**Comment by viro2** [comment]
> > It does work, see the issue I posted 2 before yours, you just whitelist the url I provided and can download a p12 cert from applep12.com Tele or I can send you one if needed
> 
> 
> 
> 
> 
> 
> 
> > It does work, see the issue I posted 2 before yours, you just whitelist the url I provided and can download a p12 cert from applep12.com Tele or I can send you one if needed
> 
> 
> 
> No, what I was referring to was make it natively possible to do something like that as ESign does
> 
> 

I'm confused as to what your asking, as in make feather work with expired certificates sake as ESign?

**Comment by Leilan1000** [comment]
> > > It does work, see the issue I posted 2 before yours, you just whitelist the url I provided and can download a p12 cert from applep12.com Tele or I can send you one if needed
> > 
> > 
> > > It does work, see the issue I posted 2 before yours, you just whitelist the url I provided and can download a p12 cert from applep12.com Tele or I can send you one if needed
> > 
> > 
> > No, what I was referring to was make it natively possible to do something like that as ESign does
> 
> I'm confused as to what your asking, as in make feather work with expired certificates sake as ESign?

Yes

**Comment by Spritzerland** [comment]
> It does work, see the issue I posted 2 before yours, you just whitelist the url I provided and can download a p12 cert from applep12.com Tele or I can send you one if needed 

could you send me one lol

**Comment by viro2** [comment]
> Yes 

Then that's what I'm explaining, I'm literally using it right now with an expired one same as ESign, all you need to do is add that url to your white list on dns and then get a free certificate from somewhere like applep12.com telegram channel

**Comment by viro2** [comment]
> > It does work, see the issue I posted 2 before yours, you just whitelist the url I provided and can download a p12 cert from applep12.com Tele or I can send you one if needed
> 
> could you send me one lol

https://t.me/AppleP12/304

**Comment by khcrysalis** [comment]
It is, just read https://github.com/khcrysalis/Feather/releases/tag/v1.0.2
