### ISSUE TITLE
I need a Anti Revoke how to make it

### ISSUE THREAD

**Issue by Leilan1000** [khcrysalis/Feather#59]

**Comment by Leilan1000** [comment]
And I have a question after the certificate expires with anti-revoke can I still sign or do I have to get a new one?

**Comment by MuzahidGithub** [comment]
broke ass

**Comment by viro2** [comment]
https://www.reddit.com/user/PuReEnVyUs/comments/1cvgqi0/free_sideloading_any_ios_no_computer_no_app_limit/ 
and no by using the dns apple cant check whether the certificate is expires so it still thinks its active so it will work even after revoked as normal
