### ISSUE TITLE
Doesn’t sign fortnite correctly 

### ISSUE THREAD

**Issue by luniz7** [khcrysalis/Feather#61]
I know this is new and it’s awesome!  Thanks for making it!

For some reason, feather can’t sign fortnite correctly. 
![IMG_3391](https://github.com/user-attachments/assets/b5d375cb-c1ae-41b7-bfb6-25a51e6d125f)

Esign can sign it just fine with the certificate I have. I’m not using an expired certificate on either.

**Comment by GottaLoveAng** [comment]
it worked for me. it's unknown why it happens but happens to some people but not everyone. also there was already a prior issue made by atellie themselves a long time ago with no resolution found there either.
