### ISSUE TITLE
Doesn’t seem to support notifications 

### ISSUE THREAD

**Issue by luniz7** [khcrysalis/Feather#62]
Apps I sign and install with a certificate with entitlements doesn’t give notifications. 

Tested same apps with Esign and same certificate with no notification issues there.

**Comment by GottaLoveAng** [comment]
turn off ppqcheck protection in settings

**Comment by luniz7** [comment]
> turn off ppqcheck protection in settings

Will give it a try. Thanks

**Comment by luniz7** [comment]
> turn off ppqcheck protection in settings

Seemed to do the trick. Thanks!

**Comment by khcrysalis** [comment]
when opening issues please close them if they're resolved!
