### ISSUE TITLE
[Enhancements] QoL Changes (if Possible)

### ISSUE THREAD

**Issue by Xiseous** [khcrysalis/Feather#64]
Hi,

Before you see the ransom demands below, I want to say thank you for a new sideloading project that already looks great and has even greater support!

Made a small list of potential QoL enhancements that are in no particular order,

- If Possible change the message "app.localhost.direct" would like to install X to say "Feather" instead.
- When cancelling installation or after installation, make the dialogue box below fade out after 3-5 seconds (maybe configurable in settings? and maybe give them animations if there's time for that in the future, like when "sending manifest" inspired by Telegram's sending files)
- Ability to change app icon through settings by uploading photo via the photos/file app (would be better if possible via files)
- Dark mode icon support 
- For Signed Apps: When resigning, allow to reconfigure the signing process again so that you don't have to keep a downloaded and not signed version.
- Setting to auto delete downloaded apps after X period (if you have to specify then 7, 14 and 30 days.)

Thanks

**Comment by khcrysalis** [comment]
> If Possible change the message "app.localhost.direct" would like to install X to say "Feather" instead.

Not possible

> When cancelling installation or after installation, make the dialogue box below fade out after 3-5 seconds (maybe configurable in settings? and maybe give them animations if there's time for that in the future, like when "sending manifest" inspired by Telegram's sending files)

Not really necessary

> Ability to change app icon through settings by uploading photo via the photos/file app (would be better if possible via files)

Not possible unless you use an external program to change the icon

> Dark mode icon support

Maybe, though it would require me downloading newer xcode which I don't have enough space for. I develop using xcode 15.1

> For Signed Apps: When resigning, allow to reconfigure the signing process again so that you don't have to keep a downloaded and not signed version.

care to explain more?

> Setting to auto delete downloaded apps after X period (if you have to specify then 7, 14 and 30 days.)

Downloaded apps should be managed by you

**Comment by Xiseous** [comment]
> For Signed Apps: When resigning, allow to reconfigure the signing process again so that you don't have to keep a downloaded and not signed version.

When downloading an app and signing it once, it will appear under the signed apps, from here if you choose to resign the app again, you'll no longer get the same options as you do when you first downloaded the app

**Comment by khcrysalis** [comment]
I will consider
