### ISSUE TITLE
Give more of a description of what's injected into the application

### ISSUE THREAD

**Issue by Ngsaints29** [khcrysalis/Feather#67]
For example if instagram is injected with Regram or Rocket then have that in the description so people know which version of Instagram they're signing. Like how Esign shows in the picture.   ![image](https://github.com/user-attachments/assets/6f12a377-8223-47ac-9381-4868ff331125)

**Comment by khcrysalis** [comment]
Already a feature in appearance!

**Comment by Ngsaints29** [comment]
![image](https://github.com/user-attachments/assets/c9af1588-6c9e-4f28-9511-d673f1ccaac3)

Where is the feature at because I'm not seeing it. It just gives you instagram and the version of instagram that's it

**Comment by khcrysalis** [comment]
I just said, its a setting in appearance

**Comment by khcrysalis** [comment]
![image](https://github.com/user-attachments/assets/c9919eb6-5b00-4ad0-a401-e0a04520ead8)
