### ISSUE TITLE
[Enhancements] Add an app preview view

### ISSUE THREAD

**Issue by Balackburn** [khcrysalis/Feather#68]
Like this https://therealfoxster.github.io/altsource-viewer/view/app/?source=https://raw.githubusercontent.com/Balackburn/YTLitePlusAltstore/main/apps.json&id=com.google.ios.youtube

![Screenshot 2024-09-20 at 02-52-44 YTLitePlus - YTLitePlus](https://github.com/user-attachments/assets/911430d9-6878-44b5-b834-5e5b65c8e64e)

**Comment by AushevAhmad** [comment]
Select "Default Subtitle" in Display settings
<img width="375" alt="image" src="https://github.com/user-attachments/assets/17c5b69a-1f6f-4db0-a901-68918ef26f70">

**Comment by Balackburn** [comment]
It's not the same as the feature I am requesting, I speak about clicking on the app and get an appstore / altstore like app view with all the detailled informations, latest release previous release etc.

**Comment by AushevAhmad** [comment]
Oh.. sorry, misunderstood.
