### ISSUE TITLE
Appstore like UI

### ISSUE THREAD

**Issue by jjr03** [khcrysalis/Feather#69]
Hope that you can make appstore-like tab wherr all apps from all repos will appear with the newest ones on top like in this image
![IMG_3620](https://github.com/user-attachments/assets/bc53a237-74fb-42fa-80b6-b070b5c839ff)

**Comment by DavidAGInnovation** [comment]
Agreed!

**Comment by khcrysalis** [comment]
Added in https://github.com/khcrysalis/Feather/commit/9a6c604aeeece5b00285971c6023fd4fbe97c147, will be available next release.
