### ISSUE TITLE
Inject tweaks without certificate

### ISSUE THREAD

**Issue by Zyanoo** [khcrysalis/Feather#7]
I'm a Trollstore user, I just want to inject tweaks and export ipa directly on my iPhone. It would be great if this feature could work without needing to add a certificate. Thanks for the lightweight and great UI app.

**Comment by khcrysalis** [comment]
Well the entire idea originally was to only provide for Feather users, though also doesn't trollstore already have a few applications which can lead to you loading tweaks inside of apps?
