### ISSUE TITLE
dylib manager and app list for all repos combined

### ISSUE THREAD

**Issue by M1noa** [khcrysalis/Feather#71]
if i could import dylib files that would make the app so much better, and a app store tab like esign where it has all apps from all repos would be a great idea for convenience

**Comment by khcrysalis** [comment]
Both of these exist already.

**Comment by M1noa** [comment]
> Both of these exist already.

 an you give me the ticket, or do you mean they already exist in app

**Comment by khcrysalis** [comment]
they exist in app, you're able to browse apps and inject dylibs.
