### ISSUE TITLE
import ipa from url

### ISSUE THREAD

**Issue by M1noa** [khcrysalis/Feather#72]
when i go to the library tab i see there no way to import from a url, like a direct download to an ipa. esign has this

**Comment by binnichtaktiv** [comment]
Yes would be nice I wanted to request the same feature

**Comment by GottaLoveAng** [comment]
![image](https://github.com/user-attachments/assets/d0c9ac66-8339-4ac2-8408-a730eea73aab)

i've requested this before so it's likely not going to happen

**Comment by binnichtaktiv** [comment]
> ![image](https://private-user-images.githubusercontent.com/76190350/370383287-d0c9ac66-8339-4ac2-8408-a730eea73aab.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxOTgyNzksIm5iZiI6MTcyNzE5Nzk3OSwicGF0aCI6Ii83NjE5MDM1MC8zNzAzODMyODctZDBjOWFjNjYtODMzOS00YWMyLTg0MDgtYTczMGVlYTczYWFiLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNFQxNzEyNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZDQyM2ZjNDljNDY4MGEzY2RhMTQ2MjMxMDBiYTIwZDYyNGVlZTBmN2U4MThkZmY3Yjc0M2IxNjZmZjY1N2I3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.yfzpeJykr64MZ_HOrBKCTEbl5hJFka65SsG4G3PuWQM)
> 
> i've requested this before so it's likely not going to happen

Damn I just don’t want to download them to files and then import to feather. Just download and directly import in feather 🙁

**Comment by khcrysalis** [comment]
Added in https://github.com/khcrysalis/Feather/releases/tag/v1.0.3
