### ISSUE TITLE
Date and description of the apps

### ISSUE THREAD

**Issue by DavidAGInnovation** [khcrysalis/Feather#77]
Hi,

I've just tested this app, and it's great, I like it much better than eSign. It has an amazing design and works pretty well.

However, I've noticed a few easy things to fix/have that the app should consider to be a better option than eSign:

1. Inside the sources section, when you see the apps from every source, apart from showing the title and description of the apps, it would be nice to show the date on which the source uploaded it.

2. I believe there's a bug with the app descriptions, as it's not showing the correct description of the apps as eSign does, it shows "a fantastic app" as a description for every app.

3. Currently, the bottom has three sections: Sources, Library and Settings. I think it would be a good feature to have a fourth section named Apps (for instance), displaying all the apps from your sources (an equivalent of AppSource on eSign).

With these changes, I believe this app would be the new number 1 for sideloading!

I'll be waiting for your revisions and updates. Thank you.

**Comment by khcrysalis** [comment]
> I believe there's a bug with the app descriptions, as it's not showing the correct description of the apps as eSign does, it shows "a fantastic app" as a description for every app.

Theres 2 types of descriptions for apps, a localizedDescription and a subtitle.

You can already customise these within the display settings.

**Comment by khcrysalis** [comment]
![image](https://github.com/user-attachments/assets/f5594473-6e5f-4318-9070-25ebc2e42c09)

**Comment by DavidAGInnovation** [comment]
![IMG_2822](https://github.com/user-attachments/assets/6fcbd1cd-93ed-4083-868c-29b58c96a277)

How can I modify it? It’s showing “it’s a fantastic app” on every app.

**Comment by DavidAGInnovation** [comment]
![IMG_2823](https://github.com/user-attachments/assets/1547fb6f-583b-493b-a99e-f3ccb9bbd8b3)

Ah, you’re right about this one, I had to change it to this.

Well, I’ll be waiting for other proposed suggestions then. Thanks!

**Comment by khcrysalis** [comment]
Refer to https://github.com/khcrysalis/Feather/issues/45 when it comes to adding date in apps
