### ISSUE TITLE
grammar mistake in ppqcheck protections explainer dialog

### ISSUE THREAD

**Issue by jakeyounglol** [khcrysalis/Feather#79]
it says “ This is meant to avoid apple flagging your account by (trying) to make it so they're unable to associate the app **your** sideloading with one from the App Store.” (the 2nd “your” should be “you’re”)

**Comment by khcrysalis** [comment]
When trying to check for grammar mistakes make a pull request instead with your proposed changes.

**Comment by GottaLoveAng** [comment]
i made the pull request for you

**Comment by jakeyounglol** [comment]
thanks!
