### ISSUE TITLE
gay logo

### ISSUE THREAD

**Issue by SomeAspy** [khcrysalis/Feather#8]
![image](https://github.com/user-attachments/assets/c0d04b7e-b64d-43f4-9d3c-ecf3921ae4bd)
like this ,,,,
i promis it gud

🏳️‍🌈🤨

**Comment by khcrysalis** [comment]
m

**Comment by Cristiandis** [comment]
:trollface: 
![gay_feather](https://github.com/user-attachments/assets/f2305399-fb0b-46c7-bc84-2379e0316e2a)

**Comment by SomeAspy** [comment]
Blurple :husk:

**Comment by TomerGamerTV** [comment]
The default one cannot be changed anyway

**Comment by SomeAspy** [comment]
Have you even used the app? It literally can be lmao

**Comment by TomerGamerTV** [comment]
> Have you even used the app? It literally can be lmao - I suggest you check out the app's features before you make false claims to support your dislike of LGBT ![image](https://private-user-images.githubusercontent.com/33640860/361556971-61960614-a5e4-4c00-b1e6-c77f3079f4ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3MTk0MjQsIm5iZiI6MTcyNDcxOTEyNCwicGF0aCI6Ii8zMzY0MDg2MC8zNjE1NTY5NzEtNjE5NjA2MTQtYTVlNC00YzAwLWIxZTYtYzc3ZjMwNzlmNGVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDAwMzg0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjODcxMmIzYzU0ZWFjMjE2Y2JjNzM0MDU4YmE5NmU3N2RmMzI5NjUyOTYwMmRmYmU2NDFkZTM1MTlhMWRhM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PkocZPhmxRemK_jQfGa9Sd6yeooPezNNZI7yw1QhOwI)

Do you really think I didn’t try? I keep clicking and it doesn’t switch. It also doesn’t seems like you switched the icon in the app, show me it actually works.

I also didn’t say anything about LGBT.

**Comment by SomeAspy** [comment]
I used it in a testing pre-release. It looks like that functionality has been broken since.
As for the LGBT part, there's no other reason to shoot down adding another app icon.

**Comment by khcrysalis** [comment]
No fighting please

**Comment by AushevAhmad** [comment]
> No fighting please

Discord is now even on Github :trolley:

**Comment by JCReed97-X** [comment]
I’d love to get a dark mode/ black icon option

**Comment by MuzahidGithub** [comment]
add jew logo

**Comment by khcrysalis** [comment]
For now I'll close this because I don't plan on adding any more icons right now
