### ISSUE TITLE
Invalid JSON error

### ISSUE THREAD

**Issue by FilipinoRepo** [khcrysalis/Feather#83]
almost all of the repos I try keep getting this invalid json error.![image](https://github.com/user-attachments/assets/55f89d1f-f63d-425e-8108-2b7c7c7eb315)

**Comment by khcrysalis** [comment]
Check your input

**Comment by FilipinoRepo** [comment]
> input

I copy and paste my urls from the source. I don't think that's the problem

**Comment by FilipinoRepo** [comment]
> What repo is it

driftywinds

**Comment by FilipinoRepo** [comment]
and a copy paste thing to add a few repos at once

**Comment by khcrysalis** [comment]
I dont know that url, send it here like you did pasting it in the feather text box

**Comment by FilipinoRepo** [comment]
> I dont know that url, send it here like you did pasting it in the feather text box

altstore://source?url=https://raw.githubusercontent.com/driftywinds/driftywinds.github.io/master/AltStore/apps.json

**Comment by FilipinoRepo** [comment]
here's the other thing

**Comment by FilipinoRepo** [comment]
source[5GHxhb1U7Lc5jIMpumASbN2teg9dyK5EAazzwnfm1/gPKQPTWzcz/GqlPDc/7Km2PMYo6ZLWw8aBN0jFOyphsztwijHaOP/HgNtFseMyB1X3pIk160RewkryDBOO3lYEn1vYXVzQp6qN4HcSSLFlGwnKEsOOtBr35cueB03dmxMyY1Qg36zceyW94Lvj3KnjrespEdmy81mQXjZdEkfvusBgMY9tx3QGxf7wHuZb8c7S6dH+8Yiefb6/CJdnNReBWDWNJElk7pemB1AOHyGz91gf5G3LceM1YMYlu2Uz+cOVCf8xr1PhW1YCv2DOxkgO+ZtHkm/ZHWlwCgN6ihf1dor4cg8avPhru+Dizud1YPOKbty8QFMVZeEYjydTEc22Vc8z1vLY9uoSqkkC2KGLR//WJOkbUuFRGUgICFesTlR1BDRpUyu8UDfJimXMKgb3hkh6CQ5/5OS3iuDYbFPsKV+7fj1xCt0j6/ag2RjXHxdmp02l8QRl+Jnmp6JVBPww4bUZwS+PQxhca4O0mFwGzO45PMclfxi9NASGxKor/61bgHvBLz/2RbBzmbyRM8lGjtmxoFMn1xAJYPC6vATs0XKgl12eMxSAK1ZmT/ikcagjYah31EAIpGKIZXIBGus4HJrwjfejevb4D2CujEa2osjjcmAunCHfqf5mc77QIB9nzT9r6WrhFTSrdqJ1gwNdalZrxLP6o8aC5RgTllnEwmeAmJArnG2U6k0DD/A2O6U9ZeQ8hKO35qtVHFKOXQ7yQTLdQZ6CPpbZ1DcYkWhXjzVgzIkvyDW/+9abspykP6jqH2iNPOQSRFBZnnbnsEghBz/FspJmrKZem8aLs1xZbMgWWN0xjbOr5UGuh2usf6BIxI15wIWFKLPlYWsF0q5vgxPJrSkfYHJ12N7mzeoufMchEaEpSD+AiHoHKzsBVxQlCP9vb/cvTC9TjpwDjHNbGut6Knk3ycn5ZDzGBIF7KPSfMdMuPZ3DVKm2Z/Y7//veUYyDiTCL7qkARIsnH1ChDkUzdp7uEW38W02yBMn2LH/81TRLNcXQdsQQ/Jg7EtHWBrFhDvYJvrh7uKpbvKidJISIYJkV15HeK/dv7xzFnWPVi+44yzz9k1kxG9qYrEhi7oRvcFKVtavxa6sDzyTLm3COUf1ZdoYoF3ZGf0vE5Id/x8AW+oV5/FZkxC3k8tgEVGciqYCCILD0u6X7mP1Jrvjg5T0xfVO94ZHh0E2xhLja009ZmaDR3JwFbzgOEw9jlqth4+Bg3TPVp89DlbarkpUIdL0eqeOWmBfmYzt2ebQXfg3Yt9cZo6LrJgXtlvo5CWwZRr8On5yK+3Jm0D9PlRGt4dTXCXXBw+fZqtH5kkEwJJHqxIcbgDoBE8Ieb9aKWEF/vcLvN9lPLugex/pO4CFGYUOE+ZcTNYJoLr2fuctFbSFPi5Tb0aKqXxVQZlKSz7YVee4eiAub1r+f9VskvJ7jb1xOAKuSIgjKRYcJYgHekrOy/JV2WfcBE35LB4LPBZLSA3H+YwdkyenoVKv4z2UicQVoiajgvWMlRsNFi/+2aO5ck4rQeNlahyOprSIUzRH2iNoRXRXbB5Jszobe2EoZycYncQifcRXdGteoIpefasxDzRqykyB/uJcbBlSEb70cuNTIR/RWrRdUKXVi5NxDfMyzorQDjBaLBjGS7+Gda+IYqy6cxRVJNoTkiymUGRcvx/qEatvT2EqCUFFRtRIjb+SVpNzrz+hwar/tmLMTndPNJFVKqJQr5jUEKz/5xv3O95vN28PFWqEQlrmZpuupKs8YCh8FaSj1dguMGGbuxiap2T+VMUa0w8BKpb40q8AST+iFnxR/iz+oYR2o+EfVgo3DtLsLAKGmDxRhckztSqv2tpRK9f8qW1O9JTCoHtyds3nml3kTzTH77QLJZnll+3990A+6RiG/nBuGMt0PTa1wdKuHolYhSHkcvISKK874tO6plGLn4ZfK0OZmW0EtMJB16Mg5ys/X9LG+rFc=]

**Comment by khcrysalis** [comment]
so copy the link with it only starting with https, then paste it in feather

**Comment by khcrysalis** [comment]
This "repo" would most likely give an error when adding, because it doesnt follow the correct repository format provided by altstore themselves

**Comment by khcrysalis** [comment]
Feather doesnt support esign exported repos

**Comment by FilipinoRepo** [comment]
> so copy the link with it only starting with https, then paste it in feather. It's highlighted blue on github

it worked lol thx

**Comment by FilipinoRepo** [comment]
> Feather doesnt support esign exported repos

do you know how to fix the other thing tho?

**Comment by khcrysalis** [comment]
Esign exported repos are intentionally obfuscated so other apps arent able to read it.

**Comment by FilipinoRepo** [comment]
> Esign exported repos are intentionally obfuscated so other apps arent able to read it.

ah
