### ISSUE TITLE
blue app icon after install

### ISSUE THREAD

**Issue by FilipinoRepo** [khcrysalis/Feather#84]
whenever I install an app, it just shows as an blue icon

**Comment by FilipinoRepo** [comment]
![image](https://github.com/user-attachments/assets/9d622b0e-edce-4400-8fbd-c393e2709100)

**Comment by khcrysalis** [comment]
Its a bug on ios, restart the device

**Comment by FilipinoRepo** [comment]
> Its a bug on ios, restart the device

k

**Comment by FilipinoRepo** [comment]
> Its a bug on ios, restart the device

uh it’s still blue

**Comment by FilipinoRepo** [comment]
what now

**Comment by FilipinoRepo** [comment]
nvm

**Comment by FilipinoRepo** [comment]
annoying that I have restart everytime I install
