### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by engproali** [khcrysalis/Feather#86]
First thanx for the amazing app
Please add auto install after signing the app just like esign
And is there a way to delete unnecessary folders of the installed apps like automatically deleting the unsigned app folder after the imported app signed secessfully?

**Comment by khcrysalis** [comment]
> I'd like the ability to delete the folders as well because when I manually do it shows an entry saying it's been deleted and I have to remove it manually. 🤪

![image](https://github.com/user-attachments/assets/6f6f0a39-bc71-49aa-9e17-5170efd0ced5)

This is how you delete the folder as well. You're not supposed to delete them manually inside of the files app.

**Comment by khcrysalis** [comment]
added in https://github.com/khcrysalis/Feather/releases/tag/v1.0.3
