### ISSUE TITLE
Feather Version updates install new instance

### ISSUE THREAD

**Issue by acgorecki** [khcrysalis/Feather#88]
When a new version of Feather is released and installed through the app, it creates an entirely new app that requires setting up a certificate and adding repos and apps, etc. basically it starts over…

Ideally, the version updates would install over the current app (like when you update from the App Store) so all settings persist.

**Comment by khcrysalis** [comment]
> When a new version of Feather is released and installed through the app, it creates an entirely new app that requires setting up a certificate and adding repos and apps, etc. basically it starts over…

It's because feather prepends a set random string to the bundle identifier by default, you can disable this in settings.

Also, installing feather on top of itself is not recommended as it would make feather crash.
