### ISSUE TITLE
Add search application from repository

### ISSUE THREAD

**Issue by Am1nCmd** [khcrysalis/Feather#9]
It would be nice to have searching application from repository instead of just search repository

**Comment by khcrysalis** [comment]
That's already on one of my to-do's, will most likely be added either next update or a future update.

Though keep this issue open until it's added so I can keep track!

**Comment by Am1nCmd** [comment]
Awesome. Great to hear that. Thx you in advance

**Comment by TomerGamerTV** [comment]
> That's already on one of my to-do's, will most likely be added either next update or a future update.
> 
> Though keep this issue open until it's added so I can keep track!

Can you show your todo list on the readme?

**Comment by khcrysalis** [comment]
https://github.com/khcrysalis/Feather/releases/tag/v1.0.1 has been released, with a feature for this!
