### ISSUE TITLE
[Suggest] Make ability to add GBox Repos

### ISSUE THREAD

**Issue by mikhailfluffy** [khcrysalis/Feather#97]
My suggestion is make ability to add GBox Repos.
Why not?

**Comment by mikhailfluffy** [comment]
[jngzxskldfjkdsljfksjdkflsjdkfljsdkfjdskfj.json](https://github.com/user-attachments/files/17198460/jngzxskldfjkdsljfksjdkflsjdkfljsdkfjdskfj.json)

or https://repo.starfiles.co/ , https://gbox.pub/Public/Source.json

**Comment by khcrysalis** [comment]
These are entirely new repo formats that seem like a waste of time.
starfiles works fine though.
