### ISSUE TITLE
Ability to update Feather via Feather

### ISSUE THREAD

**Issue by hostedbyjustus** [khcrysalis/Feather#99]
As someone who installed Feather via the signing service I'm subscribed to, I'd love to update Feather via Feather without losing data. 

I also noticed that generally updating apps isn't very straightforward and the app may install as another app. 

These are the only issues I really currently have. Great app and even better with improvements :)

**Comment by khcrysalis** [comment]
It only installs as another app because of its different bundle identifier. Feather applies it automatically with the PPQCheck option.

You must use an alternative software to install feather as installing over itself will crash the app when you're inside the app. Thus, failing.

**Comment by khcrysalis** [comment]
Make sure when updating feature that you use the same bundle identifier, if you do data will retain.

**Comment by hostedbyjustus** [comment]
Pretty sure I'm always installing apps with the same bundle ID. Could enabling options be the culprit? I guess it could also be some 1.0 thing. Anyways, thanks for letting me know.

**Comment by khcrysalis** [comment]
> Pretty sure I'm always installing apps with the same bundle ID

Feather by default adds a random string, but regardless updating feather via feather (using the same bundle identifier) will not work as Feather would just crash in the middle of trying to update.

**Comment by afirulaf** [comment]
Just FYI Sidestore can update itself. It will close itself and a notification will popup saying Sidestore will be on homescreen after update complete.

**Comment by khcrysalis** [comment]
Both applications are in fact completely different.
